# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
cv_title: Ali Dehghani
cv_email: ali.dehghani.g@gmail.com
cv_description: "Ali Dehghani's CV"
url: "https://alidg.me"
cv_name: Ali Dehghani
cv_job: Software Engineer
cv_location: Tehran, Iran
twitter_username: alidehghanig
github_username:  alimate
email_address: ali.dehghani.g@gmail.com

# Blog specific
title: Kemikit
head_title: "Ali Dehghani's Blog"
email: ali.dehghani.g@gmail.com
description: A chemical romance bursts into the IT world

# Build settings
markdown: kramdown

# SSL
enforce_ssl: alidg.me

# Gems
plugins:
  - jekyll-feed
